version: 2

before:
  hooks:
    - go mod tidy
    - bash -c 'cd ../.. && bun install && bunx nx run @runwisp/web-ui:build'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/runwisp/runwisp/internal/version.Version={{.Version}}
    main: ./cmd/runwisp

archives:
  - format: tar.gz
    files:
      - src: ../../LICENSE
      - src: ../../NOTICE
      - src: ../../README.md
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
