// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0

// Copies the daemon's machine-readable contracts into the docs site's public/
// so they are served at stable URLs: the REST API's openapi.json and the
// runwisp.toml JSON Schema (config.schema.json, the target of the `#:schema`
// directive scaffolded configs carry). The OpenAPI spec is regenerated by the
// `runwisp:openapi` moon dep; the config schema is a committed, hand-authored
// file embedded in the binary — copied verbatim so the published copy is
// byte-identical to what `runwisp schema` prints.

import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

const artifacts: ReadonlyArray<{
    label: string;
    source: string;
    destination: string;
    hint: string;
}> = [
    {
        label: "openapi",
        source: resolve(here, "../../runwisp/openapi.json"),
        destination: resolve(here, "../public/openapi.json"),
        hint: "Run `bun run generate` (or `bunx moon run runwisp:openapi`) first.",
    },
    {
        label: "config-schema",
        source: resolve(here, "../../runwisp/internal/config/config.schema.json"),
        destination: resolve(here, "../public/config.schema.json"),
        hint: "The schema is committed at apps/runwisp/internal/config/config.schema.json.",
    },
];

for (const { label, source, destination, hint } of artifacts) {
    if (!existsSync(source)) {
        console.error(`sync-openapi: ${label} source not found at ${source}`);
        console.error(hint);
        process.exit(1);
    }
    mkdirSync(dirname(destination), { recursive: true });
    copyFileSync(source, destination);
    console.log(`sync-openapi: ${source} → ${destination}`);
}
