// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0

// Package importer converts existing crontab and supervisord configuration
// into an annotated runwisp.toml. It is the onboarding bridge for the two
// tools RunWisp replaces.
//
// The package is deliberately pure: parsers take an io.Reader (or file paths)
// and return a *Result; nothing here reaches for the clock, the network, or a
// live daemon. The CLI layer (cmd/runwisp) owns I/O, TTY prompts, and the
// final config.Load round-trip that proves the generated TOML is valid.
//
// A conversion is never silently lossy. Anything that can't map cleanly onto a
// RunWisp key — a MAILTO line, a supervisord [eventlistener], an unparseable
// cron spec — becomes a Note (and usually an inline `# TODO:` comment in the
// emitted TOML) so the operator sees exactly what needs a human.
package importer

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// Level classifies a Note. Info notes explain a mapping decision the operator
// should know about; Attention notes flag something that needs a human before
// the config is trustworthy.
type Level int

const (
	LevelInfo Level = iota
	LevelAttention
)

// Note is a single human-readable observation about the conversion. Scope is
// the task/service name it concerns, or "" for file-level notes.
type Note struct {
	Level   Level
	Scope   string
	Message string
}

// Item is a summary row for one imported task or service, used by the CLI to
// print the "✓ name  schedule" overview without re-parsing the TOML.
type Item struct {
	Name      string
	Kind      string // "task" or "service"
	Schedule  string // human-friendly: a cron expr, "@reboot", or "service"
	Attention bool   // true when this item carries an unresolved TODO
}

// Result is the outcome of a conversion: the emitted TOML (built from blocks),
// the notes, and per-item summaries.
type Result struct {
	blocks []block
	// topComments are `#` lines emitted at the very top of the TOML, right after
	// the generated-by header. They ride the stdout pipe safely (a comment is
	// valid TOML) and land in the saved file where a reviewer will see them — the
	// right place for a "this might need a human" banner.
	topComments []string
	Notes       []Note
}

// AddNote appends a note. attention=true escalates the most recent summary
// item so the CLI flags it.
func (r *Result) addNote(level Level, scope, msg string) {
	r.Notes = append(r.Notes, Note{Level: level, Scope: scope, Message: msg})
}

// Items returns the summary rows in emission order.
func (r *Result) Items() []Item {
	items := make([]Item, 0, len(r.blocks))
	for i := range r.blocks {
		b := &r.blocks[i]
		if !b.isItem {
			continue
		}
		items = append(items, Item{
			Name:      b.name,
			Kind:      b.kind,
			Schedule:  b.schedule,
			Attention: b.attention,
		})
	}
	return items
}

// Counts returns the number of imported tasks and services.
func (r *Result) Counts() (tasks, services int) {
	for i := range r.blocks {
		switch {
		case !r.blocks[i].isItem:
		case r.blocks[i].kind == "service":
			services++
		default:
			tasks++
		}
	}
	return tasks, services
}

// AttentionCount returns how many notes need a human.
func (r *Result) AttentionCount() int {
	n := 0
	for _, note := range r.Notes {
		if note.Level == LevelAttention {
			n++
		}
	}
	return n
}

// field is one `key = value` line. value is already TOML-formatted.
type field struct {
	key     string
	value   string
	comment string // trailing "# ..." note, without the leading "# "
}

// block is one TOML table — a [tasks.x] / [services.x] / [defaults] header, the
// comment lines that precede it, and its fields. A block may also describe a
// summary item (isItem) for the CLI overview.
type block struct {
	header string   // dotted path, e.g. "tasks.backup" or "defaults.env"
	lead   []string // comment lines emitted above the header, without "# "
	fields []field

	isItem    bool
	name      string
	kind      string
	schedule  string
	attention bool
}

func (b *block) set(key, value string) {
	b.fields = append(b.fields, field{key: key, value: value})
}

func (b *block) setComment(key, value, comment string) {
	b.fields = append(b.fields, field{key: key, value: value, comment: comment})
}

// TOML renders the full annotated configuration. Blocks are emitted in the
// order the parser produced them; fields keep their insertion order so the
// output mirrors the source file's logical flow.
func (r *Result) TOML() string {
	var sb strings.Builder
	sb.WriteString("# Generated by `runwisp import`. Review the notes below, then\n")
	sb.WriteString("# validate with `runwisp validate`.\n")
	for _, line := range r.topComments {
		sb.WriteString("# ")
		sb.WriteString(line)
		sb.WriteByte('\n')
	}
	for i := range r.blocks {
		b := &r.blocks[i]
		sb.WriteByte('\n')
		for _, line := range b.lead {
			sb.WriteString("# ")
			sb.WriteString(line)
			sb.WriteByte('\n')
		}
		sb.WriteByte('[')
		sb.WriteString(b.header)
		sb.WriteString("]\n")
		for _, f := range b.fields {
			sb.WriteString(f.key)
			sb.WriteString(" = ")
			sb.WriteString(f.value)
			if f.comment != "" {
				sb.WriteString("  # ")
				sb.WriteString(f.comment)
			}
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}

// --- TOML value formatting helpers ---

// tomlString formats a Go string as a TOML basic string, switching to a
// multi-line basic string when the value contains newlines (the common case
// for multi-step `run` scripts).
func tomlString(s string) string {
	if !strings.Contains(s, "\n") {
		return strconv.Quote(s)
	}
	// Multi-line basic string. Escape backslashes so the body is taken
	// literally, and guard the rare case of an embedded `"""`.
	body := strings.ReplaceAll(s, `\`, `\\`)
	body = strings.ReplaceAll(body, `"""`, `""\"`)
	return "\"\"\"\n" + body + "\"\"\""
}

// tomlIntArray formats ints as a TOML array, e.g. [0, 2].
func tomlIntArray(vals []int) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = strconv.Itoa(v)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// envBlock builds a child table (e.g. "tasks.web.env") with keys sorted for
// deterministic output. Returns false when env is empty.
func envBlock(header string, env map[string]string) (block, bool) {
	if len(env) == 0 {
		return block{}, false
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	b := block{header: header}
	for _, k := range keys {
		b.set(k, tomlString(env[k]))
	}
	return b, true
}

// deduper assigns unique, sanitized RunWisp task names. Cron and supervisord
// both yield names that can collide once sanitized (model.SanitizeTaskName
// flattens punctuation), so every generated name flows through here.
type deduper struct {
	seen map[string]int
}

func newDeduper() *deduper { return &deduper{seen: map[string]int{}} }

// unique returns base if unused, otherwise base-2, base-3, … The first
// collision for a base claims "-2" so the suffixes read naturally.
func (d *deduper) unique(base string) string {
	if _, ok := d.seen[base]; !ok {
		d.seen[base] = 1
		return base
	}
	for {
		d.seen[base]++
		candidate := fmt.Sprintf("%s-%d", base, d.seen[base])
		if _, ok := d.seen[candidate]; !ok {
			d.seen[candidate] = 1
			return candidate
		}
	}
}
