#!/usr/bin/env bash
# Post-process sqlc-generated files to remove the self-import sqlc emits when
# `overrides` point to the same package as the generated code. v1.27 has no
# flag to suppress this; the generated import is unused after stripping the
# `sqlcdb.` prefix, so we drop both.
set -euo pipefail

cd "$(dirname "$0")/.."
sqlcdb_dir="internal/storage/sqlcdb"

for f in "$sqlcdb_dir"/*.go; do
  case "$(basename "$f")" in
    enums.go|run_methods.go) continue ;;
  esac
  head -n 1 "$f" | grep -q "Code generated by sqlc" || continue

  # Portable in-place edit (BSD sed needs a backup-suffix arg with -i).
  sed -i.bak \
    -e '\|"github.com/runwisp/runwisp/internal/storage/sqlcdb"|d' \
    -e 's/sqlcdb\.//g' \
    "$f"
  rm -f "$f.bak"
done

# Normalize import grouping after the removal.
gofmt -w "$sqlcdb_dir"
