// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: GPL-3.0-or-later

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/runwisp/runwisp/internal/config"
	"github.com/runwisp/runwisp/internal/configedit"
	"github.com/runwisp/runwisp/internal/model"
	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// promoteFixture stages the two-tier layout `import cron --write` produces and
// returns the root config path. Everything the promote tests need is on disk,
// deliberately: the whole subject is which bytes end up in which file.
func promoteFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "runwisp.toml")

	require.NoError(t, os.WriteFile(cfgPath, []byte(`[daemon]
include = ["runwisp.d/*.toml"]

# my own task
[tasks.mine]
run = "echo mine"
`), 0o644))

	require.NoError(t, os.MkdirAll(filepath.Join(dir, config.ImportedStagingSubdir), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, config.ImportedStagingSubdir, config.ImportedStagingBase), []byte(`#:schema https://docs.runwisp.com/config.schema.json
# Generated by `+"`runwisp import`"+`.

# from crontab line 1
[tasks.backup]
cron = "0 3 * * *"
run = "/usr/bin/backup.sh"

[services.worker]
run = "worker --loop"
`), 0o644))

	return cfgPath
}

// promote runs the command's logic the way RunE does, returning stdout.
func promote(t *testing.T, cfgPath string, args []string, opts promoteOpts) (stdout string, err error) {
	t.Helper()
	var out bytes.Buffer
	cmd := &cobra.Command{}
	cmd.SetOut(&out)
	err = runPromote(cmd, args, Flags{CfgFile: cfgPath}, opts)
	return out.String(), err
}

func readConfigFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	return string(data)
}

func TestPromoteCmd_MovesOneTask(t *testing.T) {
	cfgPath := promoteFixture(t)
	stagingPath := config.StagingFilePath(filepath.Dir(cfgPath))

	stdout, err := promote(t, cfgPath, []string{"backup"}, promoteOpts{})
	require.NoError(t, err)

	assert.Contains(t, stdout, "Promoted 1 task into")
	assert.Contains(t, stdout, "backup")
	assert.Contains(t, stdout, "did not change", "the operator is told a promote is not a behaviour change")
	assert.Contains(t, stdout, "runwisp reload")

	root := readConfigFile(t, cfgPath)
	assert.Contains(t, root, "# from crontab line 1", "the block's comment travels with it")
	assert.Contains(t, root, "[tasks.backup]")
	assert.Contains(t, root, "# my own task", "the operator's own content is untouched")
	assert.NotContains(t, readConfigFile(t, stagingPath), "[tasks.backup]")

	cfg, err := config.Load(cfgPath)
	require.NoError(t, err)
	assert.False(t, loadedTask(t, cfg, "backup").Source == model.SourceStaged)
	assert.True(t, loadedTask(t, cfg, "worker").Source == model.SourceStaged)
}

func TestPromoteCmd_All(t *testing.T) {
	cfgPath := promoteFixture(t)
	stagingPath := config.StagingFilePath(filepath.Dir(cfgPath))

	stdout, err := promote(t, cfgPath, nil, promoteOpts{all: true})
	require.NoError(t, err)

	assert.Contains(t, stdout, "Promoted 1 task, 1 service into")
	assert.Contains(t, stdout, "held nothing else, so it was removed")

	_, statErr := os.Stat(stagingPath)
	assert.True(t, os.IsNotExist(statErr), "the emptied staging file is removed")

	cfg, err := config.Load(cfgPath)
	require.NoError(t, err)
	assert.ElementsMatch(t, []string{"mine", "backup", "worker"}, taskNames(cfg))
	for _, name := range []string{"mine", "backup", "worker"} {
		assert.False(t, loadedTask(t, cfg, name).Source == model.SourceStaged, "%s should be native now", name)
	}
}

// TestPromoteCmd_AllWithNothingStaged exits 0 rather than erroring, so re-running
// a provisioning script against an already-converged config is a no-op.
func TestPromoteCmd_AllWithNothingStaged(t *testing.T) {
	cfgPath := promoteFixture(t)
	_, err := promote(t, cfgPath, nil, promoteOpts{all: true})
	require.NoError(t, err)

	stdout, err := promote(t, cfgPath, nil, promoteOpts{all: true})

	require.NoError(t, err)
	assert.Contains(t, stdout, "Nothing to promote")
}

func TestPromoteCmd_DryRunWritesNothing(t *testing.T) {
	cfgPath := promoteFixture(t)
	stagingPath := config.StagingFilePath(filepath.Dir(cfgPath))
	rootBefore := readConfigFile(t, cfgPath)
	stagingBefore := readConfigFile(t, stagingPath)

	stdout, err := promote(t, cfgPath, nil, promoteOpts{all: true, dryRun: true})
	require.NoError(t, err)

	assert.Contains(t, stdout, "Would add 1 task, 1 service")
	assert.Contains(t, stdout, "[tasks.backup]", "the plan shows the block that would move")
	assert.Contains(t, stdout, "Nothing was written.")

	assert.Equal(t, rootBefore, readConfigFile(t, cfgPath))
	assert.Equal(t, stagingBefore, readConfigFile(t, stagingPath))
}

// cronPromoteFixture stages a root config that reads one crontab live via
// include_cron, and returns the root config path and the crontab's path.
func cronPromoteFixture(t *testing.T) (cfgPath, cronPath string) {
	t.Helper()
	dir := t.TempDir()
	cfgPath = filepath.Join(dir, "runwisp.toml")
	cronPath = filepath.Join(dir, "crontabs", "mycron")

	require.NoError(t, os.WriteFile(cfgPath, []byte(`[daemon]
include_cron = ["crontabs/*"]

# my own task
[tasks.mine]
run = "echo mine"
`), 0o644))
	require.NoError(t, os.MkdirAll(filepath.Dir(cronPath), 0o755))
	require.NoError(t, os.WriteFile(cronPath, []byte("0 3 * * * /usr/local/bin/dump.sh --full\n"), 0o644))
	return cfgPath, cronPath
}

// TestPromoteCmd_CronDryRunShowsBothSidesAndWritesNothing is the --dry-run
// contract for a live cron-sourced task: it must show the block landing in
// root *and* the crontab line that would be commented out, and touch neither
// file.
func TestPromoteCmd_CronDryRunShowsBothSidesAndWritesNothing(t *testing.T) {
	cfgPath, cronPath := cronPromoteFixture(t)
	rootBefore := readConfigFile(t, cfgPath)
	cronBefore := readConfigFile(t, cronPath)

	stdout, err := promote(t, cfgPath, []string{"dump"}, promoteOpts{dryRun: true})
	require.NoError(t, err)

	assert.Contains(t, stdout, "[tasks.dump]", "the plan shows the block that would land in root")
	assert.Contains(t, stdout, "Would comment out 1 crontab line(s)")
	assert.Contains(t, stdout, cronPath+":1: 0 3 * * * /usr/local/bin/dump.sh --full",
		"the plan names the exact file, line, and text that would be commented out")
	assert.Contains(t, stdout, "Nothing was written.")

	assert.Equal(t, rootBefore, readConfigFile(t, cfgPath))
	assert.Equal(t, cronBefore, readConfigFile(t, cronPath))
}

// TestPromoteCmd_CronPromoteCommentsOutTheCrontabLine is the end-to-end version
// of the core regression: `promote` on a live cron task moves it into root and
// comments out the source line, and says so.
func TestPromoteCmd_CronPromoteCommentsOutTheCrontabLine(t *testing.T) {
	cfgPath, cronPath := cronPromoteFixture(t)

	stdout, err := promote(t, cfgPath, []string{"dump"}, promoteOpts{})
	require.NoError(t, err)

	assert.Contains(t, stdout, "Promoted 1 task")
	assert.Contains(t, stdout, "Commented out 1 crontab line(s)")
	assert.Contains(t, stdout, cronPath+":1")
	assert.Contains(t, stdout, "a reload starts RunWisp scheduling it",
		"a live cron promotion is a real handover, not the staged path's no-op")
	assert.NotContains(t, stdout, "did not change",
		"the staged path's 'nothing changed' line must not appear for a cron handover")
	assert.Contains(t, stdout, "runwisp reload")

	assert.Contains(t, readConfigFile(t, cfgPath), "[tasks.dump]")
	crontab := readConfigFile(t, cronPath)
	assert.Contains(t, crontab, "#0 3 * * * /usr/local/bin/dump.sh --full",
		"the sole crontab line is commented out, not deleted")
	assert.Contains(t, crontab, "this job was promoted to", "with a note pointing at where it moved")
}

// TestPromoteCmd_CronSourceMismatchPhrasesCleanly pins how the CLI translates
// a *configedit.CronSourceMismatchError — the refusal a race between
// `crontab -e` and `runwisp promote` produces — into operator-facing advice
// that says plainly that nothing was written.
func TestPromoteCmd_CronSourceMismatchPhrasesCleanly(t *testing.T) {
	err := promoteError(&configedit.CronSourceMismatchError{
		Name: "dump", File: "/etc/cron.d/dump", Line: 3, Reason: "that line changed since it was read",
	}, configedit.Layout{RootPath: "runwisp.toml"})

	uf, ok := isUserFacing(err)
	require.True(t, ok, "a refusal must read as advice, not a stack trace")
	assert.Contains(t, uf.Error(), "changed underneath it")
	assert.Contains(t, uf.Error(), "/etc/cron.d/dump:3")
	assert.Contains(t, uf.Error(), "Nothing was written")
}

func TestPromoteCmd_Refusals(t *testing.T) {
	tests := []struct {
		name string
		args []string
		opts promoteOpts
		want []string
	}{
		{
			name: "no names and no --all lists what is staged",
			want: []string{"name a task to promote", "backup", "worker"},
		},
		{
			name: "--all with names",
			args: []string{"backup"},
			opts: promoteOpts{all: true},
			want: []string{"can't be combined with task names"},
		},
		{
			name: "unknown name",
			args: []string{"nope"},
			want: []string{`no task named "nope"`, "runwisp list", "Nothing was written"},
		},
		{
			name: "an already-native task names its file",
			args: []string{"mine"},
			want: []string{`"mine" is already native`, "runwisp.toml", "Nothing was written"},
		},
		{
			name: "one bad name refuses the whole request",
			args: []string{"backup", "nope"},
			want: []string{`no task named "nope"`},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			cfgPath := promoteFixture(t)
			before := readConfigFile(t, cfgPath)

			_, err := promote(t, cfgPath, tc.args, tc.opts)

			require.Error(t, err)
			_, userFacing := isUserFacing(err)
			assert.True(t, userFacing, "a refusal must read as advice, not a stack trace")
			for _, want := range tc.want {
				assert.Contains(t, err.Error(), want)
			}
			assert.Equal(t, before, readConfigFile(t, cfgPath), "a refused promote writes nothing")
		})
	}
}

// TestPromoteCmd_BrokenConfigIsRefusedUpFront: promote needs a config that loads
// to know what is staged at all, and refusing here also means a pre-existing
// problem is never reported as something the promotion did.
func TestPromoteCmd_BrokenConfigIsRefusedUpFront(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "runwisp.toml")
	require.NoError(t, os.WriteFile(cfgPath, []byte("[tasks.broken\nrun = \"x\"\n"), 0o644))

	_, err := promote(t, cfgPath, []string{"broken"}, promoteOpts{})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "it doesn't load")
	assert.Contains(t, err.Error(), "Nothing was written")
}

// TestPromoteStagedFooter is the nudge on `runwisp list` — the path by which an
// operator who never read the import summary still discovers promote.
func TestPromoteStagedFooter(t *testing.T) {
	cfgPath := promoteFixture(t)
	cfg, err := config.Load(cfgPath)
	require.NoError(t, err)

	footer := promoteStagedFooter(cfg, cfgPath)
	assert.Contains(t, footer, "2 tasks are imported or read from a crontab")
	assert.Contains(t, footer, "runwisp promote <name>")

	// Promoting one leaves singular phrasing; promoting the rest drops the footer.
	_, err = promote(t, cfgPath, []string{"backup"}, promoteOpts{})
	require.NoError(t, err)
	cfg, err = config.Load(cfgPath)
	require.NoError(t, err)
	assert.Contains(t, promoteStagedFooter(cfg, cfgPath), "1 task is imported or read from a crontab")

	_, err = promote(t, cfgPath, nil, promoteOpts{all: true})
	require.NoError(t, err)
	cfg, err = config.Load(cfgPath)
	require.NoError(t, err)
	assert.Empty(t, promoteStagedFooter(cfg, cfgPath), "no staged tasks, no nudge")
}

// TestListCmd_FooterOnlyWhenSomethingIsStaged keeps the table's own output stable
// for anything parsing it: the nudge is a footer, not a column.
func TestListCmd_FooterOnlyWhenSomethingIsStaged(t *testing.T) {
	cfgPath := promoteFixture(t)

	var staged bytes.Buffer
	require.NoError(t, runList(&staged, Flags{CfgFile: cfgPath}, false))
	assert.Contains(t, staged.String(), "NAME")
	assert.Contains(t, staged.String(), "2 tasks are imported or read from a crontab")

	_, err := promote(t, cfgPath, nil, promoteOpts{all: true})
	require.NoError(t, err)

	var native bytes.Buffer
	require.NoError(t, runList(&native, Flags{CfgFile: cfgPath}, false))
	assert.Contains(t, native.String(), "NAME")
	assert.NotContains(t, native.String(), "staged")
}
