// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0

// Generates src/generated/config.ts from runwisp.toml's JSON Schema, so every
// config key RunWisp accepts is typed here with no SDK change. openapi-typescript
// reads JSON Schema 2020-12 as OpenAPI 3.1 components; the schema's $defs
// become those components.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = join(root, "../../apps/runwisp/internal/config/config.schema.json");
const outputFile = join(root, "src/generated/config.ts");

type OpenAPISpec = Extract<Parameters<typeof openapiTS>[0], Record<string, unknown>>;

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isOpenAPISpec(value: unknown): value is OpenAPISpec {
    return isRecord(value) && isRecord(value["components"]);
}

const schema: unknown = JSON.parse(readFileSync(schemaPath, "utf8"));
if (!isRecord(schema) || !isRecord(schema["$defs"])) throw new Error(`${schemaPath} has no $defs`);
// This package is Apache-2.0 and the daemon GPL: generate only from a schema
// that is itself Apache-2.0.
const license = schema["$comment"];
if (typeof license !== "string" || !license.includes("SPDX-License-Identifier: Apache-2.0")) {
    throw new Error(`${schemaPath} must declare SPDX-License-Identifier: Apache-2.0 in $comment`);
}
const config = Object.fromEntries(Object.entries(schema).filter(([key]) => !key.startsWith("$")));
const spec: unknown = JSON.parse(
    JSON.stringify({
        openapi: "3.1.0",
        info: { title: "runwisp.toml", version: "1" },
        paths: {},
        components: { schemas: { ...schema["$defs"], Config: config } },
    }).replaceAll('"#/$defs/', '"#/components/schemas/'),
);
if (!isOpenAPISpec(spec)) throw new Error("could not wrap the schema as OpenAPI components");

// A key with a default is still optional to write.
const ast = await openapiTS(spec, { defaultNonNullable: false });

mkdirSync(dirname(outputFile), { recursive: true });
writeFileSync(
    outputFile,
    `// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-config.ts from config.schema.json. Do not edit.

${astToString(ast)}
/** A whole runwisp.toml, as the object it decodes into. */
export type Config = components["schemas"]["Config"];
/** One [tasks.<name>] table. */
export type TaskConfig = components["schemas"]["task"];
/** One [services.<name>] table. */
export type ServiceConfig = components["schemas"]["service"];
`,
);
