// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: GPL-3.0-or-later

package configedit

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// stagingDoc is a staging file shaped exactly like the one `runwisp import cron
// --write` produces: the schema directive, the generated-by header, then one
// annotated block per job — including a child [tasks.*.env] table and an
// unresolved `# TODO:` the operator still has to deal with.
const stagingDoc = `#:schema https://runwisp.com/schema/runwisp.json
# Generated by ` + "`runwisp import`" + `. Review the notes below, then
# validate with ` + "`runwisp validate`" + `.

# from crontab line 3
[tasks.backup]
cron = "0 3 * * *"
run = "/usr/local/bin/backup.sh"

[tasks.backup.env]
BACKUP_DIR = "/srv/backups"

# from crontab line 7
# TODO: MAILTO=ops@example.com has no RunWisp equivalent
[tasks.reindex]
cron = "*/5 * * * *"
run = "reindex --all"

[services.worker]
run = "worker --loop"
instances = 2
`

func TestExtractBlocks_TakesLeadCommentsAndChildTables(t *testing.T) {
	remaining, blocks, err := ExtractBlocks([]byte(stagingDoc), []string{"backup"})
	require.NoError(t, err)

	require.Len(t, blocks, 1)
	assert.Equal(t, "backup", blocks[0].Name)
	assert.Equal(t, "tasks", blocks[0].Table)
	assert.Equal(t, `# from crontab line 3
[tasks.backup]
cron = "0 3 * * *"
run = "/usr/local/bin/backup.sh"

[tasks.backup.env]
BACKUP_DIR = "/srv/backups"`, blocks[0].Text)

	// The file header stays behind — it belongs to the file, not to the first
	// block that happens to follow it.
	assert.Contains(t, string(remaining), "#:schema ")
	assert.Contains(t, string(remaining), "# Generated by")
	assert.NotContains(t, string(remaining), "[tasks.backup]")
	assert.NotContains(t, string(remaining), "BACKUP_DIR")
	// Its neighbours are untouched, lead comments included.
	assert.Contains(t, string(remaining), "# from crontab line 7")
	assert.Contains(t, string(remaining), "[tasks.reindex]")
	assert.Contains(t, string(remaining), "[services.worker]")
}

func TestExtractBlocks_KeepsUnresolvedTODOWithItsTask(t *testing.T) {
	_, blocks, err := ExtractBlocks([]byte(stagingDoc), []string{"reindex"})
	require.NoError(t, err)

	require.Len(t, blocks, 1)
	assert.Equal(t, `# from crontab line 7
# TODO: MAILTO=ops@example.com has no RunWisp equivalent
[tasks.reindex]
cron = "*/5 * * * *"
run = "reindex --all"`, blocks[0].Text)
}

func TestExtractBlocks_FindsAService(t *testing.T) {
	_, blocks, err := ExtractBlocks([]byte(stagingDoc), []string{"worker"})
	require.NoError(t, err)

	require.Len(t, blocks, 1)
	assert.Equal(t, "services", blocks[0].Table)
	assert.Equal(t, `[services.worker]
run = "worker --loop"
instances = 2`, blocks[0].Text)
}

// TestExtractBlocks_SeveralNamesAtOnce covers the splice: every range is located
// before anything is cut, so extracting more than one entry in a single call
// can't invalidate its own offsets. Blocks come back in file order, not request
// order.
func TestExtractBlocks_SeveralNamesAtOnce(t *testing.T) {
	remaining, blocks, err := ExtractBlocks([]byte(stagingDoc), []string{"worker", "backup"})
	require.NoError(t, err)

	require.Len(t, blocks, 2)
	assert.Equal(t, []string{"backup", "worker"}, []string{blocks[0].Name, blocks[1].Name})

	assert.NotContains(t, string(remaining), "[tasks.backup]")
	assert.NotContains(t, string(remaining), "[services.worker]")
	assert.Contains(t, string(remaining), "[tasks.reindex]")
}

func TestExtractBlocks_UnknownName(t *testing.T) {
	_, _, err := ExtractBlocks([]byte(stagingDoc), []string{"nope"})

	var notFound *EntryNotFoundError
	require.ErrorAs(t, err, &notFound)
	assert.Equal(t, "nope", notFound.Name)
}

// TestExtractBlocks_AmbiguousName refuses a name declared as both a task and a
// service. Such a config doesn't load, so the CLI can't reach this — but the
// extractor shouldn't pick one at random if it ever does.
func TestExtractBlocks_AmbiguousName(t *testing.T) {
	doc := `[tasks.dual]
run = "a"

[services.dual]
run = "b"
`
	_, _, err := ExtractBlocks([]byte(doc), []string{"dual"})

	var ambiguous *AmbiguousEntryError
	require.ErrorAs(t, err, &ambiguous)
	assert.Equal(t, "dual", ambiguous.Name)
}

// TestExtractBlocks_HeaderInsideMultilineRunIsNotStructure is the reason every
// boundary decision goes through scanTOMLLines. A `run` script containing a line
// that looks like a table header must not end the block early — that would leave
// half a task behind and move half of it.
func TestExtractBlocks_HeaderInsideMultilineRunIsNotStructure(t *testing.T) {
	doc := `[tasks.deploy]
run = """
echo '[tasks.decoy]'
echo '[services.decoy]'
"""
cron = "@daily"

[tasks.after]
run = "echo after"
`
	remaining, blocks, err := ExtractBlocks([]byte(doc), []string{"deploy"})
	require.NoError(t, err)

	require.Len(t, blocks, 1)
	assert.Contains(t, blocks[0].Text, "[tasks.decoy]")
	assert.Contains(t, blocks[0].Text, `cron = "@daily"`, "the key after the string must stay in the block")
	assert.Equal(t, "[tasks.after]\nrun = \"echo after\"\n", string(remaining))

	// And the decoy is not itself extractable: it was never a table.
	_, _, err = ExtractBlocks([]byte(doc), []string{"decoy"})
	assert.ErrorAs(t, err, new(*EntryNotFoundError))
}

func TestExtractBlocks_QuotedHeaderName(t *testing.T) {
	doc := `[tasks."my.job"]
run = "echo hi"

[tasks."plain"]
run = "echo plain"
`
	_, blocks, err := ExtractBlocks([]byte(doc), []string{"plain", "my.job"})
	require.NoError(t, err)

	require.Len(t, blocks, 2)
	assert.Equal(t, []string{"my.job", "plain"}, []string{blocks[0].Name, blocks[1].Name})
}

// TestExtractBlocks_Boundaries pins the start/end rules that decide how much text
// travels with an entry.
func TestExtractBlocks_Boundaries(t *testing.T) {
	tests := []struct {
		name      string
		doc       string
		want      string
		remaining string
	}{
		{
			name: "block first in file with no header comments",
			doc: `[tasks.only]
run = "echo hi"
`,
			want:      "[tasks.only]\nrun = \"echo hi\"",
			remaining: "",
		},
		{
			name: "a blank line stops the walk back over comments",
			doc: `# a note about the file as a whole

# a note about the task
[tasks.only]
run = "echo hi"
`,
			want:      "# a note about the task\n[tasks.only]\nrun = \"echo hi\"",
			remaining: "# a note about the file as a whole\n",
		},
		{
			name: "a comment attached to the next table stays with it",
			doc: `[tasks.only]
run = "one"
# belongs to second
[tasks.second]
run = "two"
`,
			want:      "[tasks.only]\nrun = \"one\"",
			remaining: "# belongs to second\n[tasks.second]\nrun = \"two\"\n",
		},
		{
			name: "trailing blank lines are left behind",
			doc: `[tasks.only]
run = "echo hi"


`,
			want:      "[tasks.only]\nrun = \"echo hi\"",
			remaining: "",
		},
		{
			name: "a singleton table ends the block",
			doc: `[tasks.only]
run = "echo hi"

[defaults]
shell = "/bin/sh"
`,
			want:      "[tasks.only]\nrun = \"echo hi\"",
			remaining: "[defaults]\nshell = \"/bin/sh\"\n",
		},
		{
			name: "an array-of-tables header ends the block",
			doc: `[tasks.only]
run = "echo hi"

[[notifier]]
type = "slack"
`,
			want:      "[tasks.only]\nrun = \"echo hi\"",
			remaining: "[[notifier]]\ntype = \"slack\"\n",
		},
		{
			name: "a same-named child of another family does not extend the block",
			doc: `[tasks.only]
run = "echo hi"

[services.only.env]
A = "1"
`,
			want:      "[tasks.only]\nrun = \"echo hi\"",
			remaining: "[services.only.env]\nA = \"1\"\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			remaining, blocks, err := ExtractBlocks([]byte(tc.doc), []string{"only"})
			require.NoError(t, err)
			require.Len(t, blocks, 1)
			assert.Equal(t, tc.want, blocks[0].Text)
			assert.Equal(t, tc.remaining, string(remaining))
		})
	}
}

// TestExtractBlocks_CollapsesTheHoleItLeaves asserts the residue is tidied: the
// staging file is machine-owned, so the gap a promoted block used to occupy is
// closed rather than accumulating across promotions.
func TestExtractBlocks_CollapsesTheHoleItLeaves(t *testing.T) {
	doc := `[tasks.a]
run = "a"

[tasks.b]
run = "b"

[tasks.c]
run = "c"
`
	remaining, _, err := ExtractBlocks([]byte(doc), []string{"b"})
	require.NoError(t, err)

	assert.Equal(t, `[tasks.a]
run = "a"

[tasks.c]
run = "c"
`, string(remaining))
}

// TestExtractBlocks_BlankLinesInsideRunSurvive is the counterpart to the residue
// tidying: blank lines inside a `run` script are part of what the task executes,
// so collapsing them would rewrite the command.
func TestExtractBlocks_BlankLinesInsideRunSurvive(t *testing.T) {
	doc := `[tasks.keep]
run = """
step one


step two
"""

[tasks.gone]
run = "bye"
`
	remaining, _, err := ExtractBlocks([]byte(doc), []string{"gone"})
	require.NoError(t, err)

	assert.Contains(t, string(remaining), "step one\n\n\nstep two")
}

func TestAppendBlocks_AppendsVerbatim(t *testing.T) {
	root := `[daemon]
include = ["runwisp.d/*.toml"]

[tasks.mine]
run = "echo mine"
`
	blocks := []Block{
		{Name: "backup", Table: "tasks", Text: "# from crontab line 3\n[tasks.backup]\nrun = \"backup.sh\""},
		{Name: "worker", Table: "services", Text: "[services.worker]\nrun = \"worker\""},
	}

	got := string(AppendBlocks([]byte(root), blocks))

	assert.Equal(t, root+`
# from crontab line 3
[tasks.backup]
run = "backup.sh"

[services.worker]
run = "worker"
`, got)
}

// TestAppendBlocks_RootWithoutTrailingNewline guards the fusing case: appending
// to a file whose last line has no newline must not splice the block onto it.
func TestAppendBlocks_RootWithoutTrailingNewline(t *testing.T) {
	got := string(AppendBlocks([]byte(`[tasks.mine]
run = "echo mine"`), []Block{{Text: "[tasks.new]\nrun = \"new\""}}))

	assert.Equal(t, `[tasks.mine]
run = "echo mine"

[tasks.new]
run = "new"
`, got)
}

// TestExtractThenAppend_RoundTripsTheBytes is the guarantee `promote` sells: the
// bytes that leave the staging file are the bytes that arrive in the root, so
// comments and formatting survive a move that a parse/re-render never would.
func TestExtractThenAppend_RoundTripsTheBytes(t *testing.T) {
	remaining, blocks, err := ExtractBlocks([]byte(stagingDoc), []string{"reindex"})
	require.NoError(t, err)

	root := string(AppendBlocks([]byte("[daemon]\ninclude = [\"runwisp.d/*.toml\"]\n"), blocks))

	assert.Contains(t, root, "# TODO: MAILTO=ops@example.com has no RunWisp equivalent")
	assert.Contains(t, root, "# from crontab line 7")
	assert.Contains(t, root, "[tasks.reindex]")
	assert.NotContains(t, string(remaining), "MAILTO")
}

func TestHasEntries(t *testing.T) {
	tests := []struct {
		name string
		doc  string
		want bool
	}{
		{name: "empty", doc: "", want: false},
		{name: "header comments only", doc: "#:schema x\n# Generated by runwisp import\n", want: false},
		{name: "a task", doc: "[tasks.a]\nrun = \"a\"\n", want: true},
		{name: "a service", doc: "[services.a]\nrun = \"a\"\n", want: true},
		{name: "a compose project", doc: "[compose.stack]\nfile = \"c.yml\"\n", want: true},
		{name: "a singleton only", doc: "[defaults]\nshell = \"/bin/sh\"\n", want: false},
		{
			name: "a task name inside a run script is not an entry",
			doc:  "# left over\n# run = \"\"\"\n[defaults]\nshell = \"/bin/sh\"\n",
			want: false,
		},
		{
			name: "a header inside a multi-line string is not an entry",
			doc:  "[defaults]\nshell = \"\"\"\n[tasks.decoy]\n\"\"\"\n",
			want: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, HasEntries([]byte(tc.doc)))
		})
	}
}

func TestSplitDottedKey(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  []string
		ok    bool
	}{
		{name: "bare", input: "tasks.backup", want: []string{"tasks", "backup"}, ok: true},
		{name: "single segment", input: "daemon", want: []string{"daemon"}, ok: true},
		{name: "child table", input: "tasks.backup.env", want: []string{"tasks", "backup", "env"}, ok: true},
		{name: "spaced", input: " tasks . backup ", want: []string{"tasks", "backup"}, ok: true},
		{name: "quoted basic", input: `tasks."backup"`, want: []string{"tasks", "backup"}, ok: true},
		{name: "quoted with a dot", input: `tasks."my.job"`, want: []string{"tasks", "my.job"}, ok: true},
		{name: "quoted literal", input: `tasks.'my.job'`, want: []string{"tasks", "my.job"}, ok: true},
		{name: "escaped quote", input: `tasks."say\"hi"`, want: []string{"tasks", `say"hi`}, ok: true},
		{name: "quoted child", input: `tasks."my.job".env`, want: []string{"tasks", "my.job", "env"}, ok: true},
		{name: "unterminated quote", input: `tasks."backup`, ok: false},
		{name: "empty segment", input: "tasks..backup", ok: false},
		{name: "trailing dot", input: "tasks.", ok: false},
		{name: "empty", input: "", ok: false},
		{name: "junk after a quoted segment", input: `tasks."a"b`, ok: false},
		{name: "bad escape", input: `tasks."a\q"`, ok: false},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := splitDottedKey(tc.input)
			assert.Equal(t, tc.ok, ok)
			if tc.ok {
				assert.Equal(t, tc.want, got)
			}
		})
	}
}

// TestExtractBlocks_UnreadableHeaderEndsTheBlock keeps the extractor
// conservative: a header it can't parse is still a header, so the block stops
// there rather than swallowing a table it doesn't understand.
func TestExtractBlocks_UnreadableHeaderEndsTheBlock(t *testing.T) {
	doc := "[tasks.only]\nrun = \"hi\"\n[tasks.\"unterminated]\nrun = \"x\"\n"

	_, blocks, err := ExtractBlocks([]byte(doc), []string{"only"})
	require.NoError(t, err)

	require.Len(t, blocks, 1)
	assert.False(t, strings.Contains(blocks[0].Text, "unterminated"))
}
