// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0

package configedit

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/runwisp/runwisp/internal/config"
	"github.com/runwisp/runwisp/internal/model"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// twoTierRoot is the root config `runwisp import --write` leaves behind: the
// operator's own tasks plus the include line that picks up the staging dir.
const twoTierRoot = `[daemon]
include = ["runwisp.d/*.toml"]

# my own task, hand-authored
[tasks.mine]
cron = "@daily"
run = "echo mine"
`

// twoTierStaging is what the importer wrote into runwisp.d/imported.toml.
const twoTierStaging = `#:schema https://runwisp.com/schema/runwisp.json
# Generated by ` + "`runwisp import`" + `. Review the notes below, then
# validate with ` + "`runwisp validate`" + `.

# from crontab line 3
[tasks.backup]
cron = "0 3 * * *"
run = """
tar -czf /srv/backups/db.tgz /var/lib/db

echo done
"""

[tasks.backup.env]
BACKUP_DIR = "/srv/backups"

# TODO: MAILTO=ops@example.com has no RunWisp equivalent
[tasks.reindex]
cron = "*/5 * * * *"
run = "reindex --all"
`

// twoTierLayout stages a root + staging pair and returns the layout over them.
func twoTierLayout(t *testing.T, root, staging string) Layout {
	t.Helper()
	files := map[string]string{"runwisp.toml": root}
	if staging != "" {
		files[filepath.Join(config.ImportedStagingSubdir, config.ImportedStagingBase)] = staging
	}
	dir := writeFileTree(t, files)
	return NewLayout(filepath.Join(dir, "runwisp.toml"))
}

// loadLayout loads the merged config, which is what `promote` needs before it can
// decide anything.
func loadLayout(t *testing.T, layout Layout) *config.Config {
	t.Helper()
	cfg, err := config.Load(layout.RootPath)
	require.NoError(t, err)
	return cfg
}

func TestPromote_MovesTheBlockIntoTheRoot(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)

	res, err := Promote(PromoteRequest{Layout: layout, Config: loadLayout(t, layout), Names: []string{"backup"}})
	require.NoError(t, err)

	assert.False(t, res.StagingRemoved, "reindex is still staged")
	require.Len(t, res.Promoted, 1)

	root := readFile(t, layout.RootPath)
	staging := readFile(t, layout.StagingPath)

	// The block, its lead comment, and its child table all landed in the root.
	assert.Contains(t, root, "# from crontab line 3")
	assert.Contains(t, root, "[tasks.backup]")
	assert.Contains(t, root, "[tasks.backup.env]")
	// The multi-line run script survives byte-for-byte, blank line included —
	// this is what a parse/re-render round-trip would have destroyed.
	assert.Contains(t, root, "tar -czf /srv/backups/db.tgz /var/lib/db\n\necho done\n")
	// The operator's own task is untouched, comment and all.
	assert.Contains(t, root, "# my own task, hand-authored")

	assert.NotContains(t, staging, "[tasks.backup]")
	assert.NotContains(t, staging, "BACKUP_DIR")
	assert.Contains(t, staging, "[tasks.reindex]")
	assert.Contains(t, staging, "#:schema ", "the staging file keeps its own header")

	// And the merged config still sees both tasks exactly once.
	cfg := loadLayout(t, layout)
	assert.ElementsMatch(t, []string{"mine", "backup", "reindex"}, taskNames(cfg))
	assert.False(t, findTask(t, cfg, "backup").Source == model.SourceStaged, "the promoted task is native now")
	assert.True(t, findTask(t, cfg, "reindex").Source == model.SourceStaged)
}

// TestPromote_UnresolvedTODOTravelsWithTheTask is why promote is a text move: the
// importer's warning has to follow the task into the operator's file, or the
// operator loses the one note telling them something still needs a human.
func TestPromote_UnresolvedTODOTravelsWithTheTask(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)

	_, err := Promote(PromoteRequest{Layout: layout, Config: loadLayout(t, layout), Names: []string{"reindex"}})
	require.NoError(t, err)

	assert.Contains(t, readFile(t, layout.RootPath),
		"# TODO: MAILTO=ops@example.com has no RunWisp equivalent")
}

// TestPromote_RemovesTheEmptiedStagingFile: an imported.toml with nothing but a
// header would read as if it still had something to say.
func TestPromote_RemovesTheEmptiedStagingFile(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)

	res, err := Promote(PromoteRequest{Layout: layout, Config: loadLayout(t, layout), Names: []string{"backup", "reindex"}})
	require.NoError(t, err)

	assert.True(t, res.StagingRemoved)
	_, statErr := os.Stat(layout.StagingPath)
	assert.True(t, os.IsNotExist(statErr))

	// The root still loads with everything, and nothing is staged any more.
	cfg := loadLayout(t, layout)
	assert.ElementsMatch(t, []string{"mine", "backup", "reindex"}, taskNames(cfg))
	assert.Empty(t, StagedNames(cfg, layout))
}

// TestPromote_KeepsTheStagingFileWhenSomethingElseRemains guards the other side
// of that decision.
func TestPromote_KeepsTheStagingFileWhenSomethingElseRemains(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)

	res, err := Promote(PromoteRequest{Layout: layout, Config: loadLayout(t, layout), Names: []string{"reindex"}})
	require.NoError(t, err)

	assert.False(t, res.StagingRemoved)
	assert.Contains(t, readFile(t, layout.StagingPath), "[tasks.backup]")
}

// TestPromote_ConflictRollsBackBothFiles: the merged-load gate is the safety net
// for a bad extraction. If it fires, neither file may be left changed — a
// half-applied move would either duplicate a task across two files (which
// doesn't load) or lose it from both (which silently drops a job).
func TestPromote_ConflictRollsBackBothFiles(t *testing.T) {
	// The root already defines `backup`, so appending the staged block puts the
	// name in that one file twice and the merged load refuses it.
	root := `[daemon]
include = ["runwisp.d/*.toml"]

[tasks.mine]
run = "echo mine"
`
	staging := `[tasks.backup]
run = "backup.sh"

[tasks.spare]
run = "spare"
`
	layout := twoTierLayout(t, root, staging)
	require.NoError(t, os.WriteFile(layout.RootPath, []byte(root+"\n[tasks.backup]\nrun = \"mine's backup\"\n"), 0o644))
	rootBefore := readFile(t, layout.RootPath)
	stagingBefore := readFile(t, layout.StagingPath)

	// No Config: this root deliberately doesn't load, so there is none to pass.
	// Promote must still classify "backup" as staged and roll the move back.
	_, err := Promote(PromoteRequest{Layout: layout, Names: []string{"backup"}})

	var conflict *ConflictError
	require.ErrorAs(t, err, &conflict)
	assert.Equal(t, rootBefore, readFile(t, layout.RootPath), "the root must be byte-identical")
	assert.Equal(t, stagingBefore, readFile(t, layout.StagingPath), "the staging file must be byte-identical")
}

// TestPromote_PreservesRestrictiveModes: a config the operator locked down stays
// locked down after a promote.
func TestPromote_PreservesRestrictiveModes(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)
	require.NoError(t, os.Chmod(layout.RootPath, 0o600))
	require.NoError(t, os.Chmod(layout.StagingPath, 0o600))

	_, err := Promote(PromoteRequest{Layout: layout, Config: loadLayout(t, layout), Names: []string{"backup"}})
	require.NoError(t, err)

	for _, path := range []string{layout.RootPath, layout.StagingPath} {
		info, err := os.Stat(path)
		require.NoError(t, err)
		assert.Equal(t, os.FileMode(0o600), info.Mode().Perm(), path)
	}
}

func TestPromote_NoNamesWritesNothing(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)
	before := readFile(t, layout.RootPath)

	res, err := Promote(PromoteRequest{Layout: layout})
	require.NoError(t, err)

	assert.Empty(t, res.Promoted)
	assert.Equal(t, before, readFile(t, layout.RootPath))
}

func TestStagedNames_OnlyTheStagingFile(t *testing.T) {
	root := `[daemon]
include = ["runwisp.d/*.toml", "conf.d/*.toml"]

[tasks.native]
run = "echo native"
`
	dir := writeFileTree(t, map[string]string{
		"runwisp.toml":                "",
		"conf.d/hand.toml":            "[tasks.hand]\nrun = \"echo hand\"\n",
		"runwisp.d/imported.toml":     "[tasks.staged_one]\nrun = \"a\"\n\n[services.staged_two]\nrun = \"b\"\n",
		"runwisp.d/also_imported.tml": "ignored: not a .toml\n",
	})
	require.NoError(t, os.WriteFile(filepath.Join(dir, "runwisp.toml"), []byte(root), 0o644))
	layout := NewLayout(filepath.Join(dir, "runwisp.toml"))

	got := StagedNames(loadLayout(t, layout), layout)

	assert.ElementsMatch(t, []string{"staged_one", "staged_two"}, got)
}

func TestSelect(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, twoTierStaging)
	cfg := loadLayout(t, layout)

	t.Run("all takes every staged entry", func(t *testing.T) {
		got, err := Select(cfg, layout, nil, true)
		require.NoError(t, err)
		assert.ElementsMatch(t, []string{"backup", "reindex"}, got)
	})

	t.Run("named entries keep the operator's order", func(t *testing.T) {
		got, err := Select(cfg, layout, []string{"reindex", "backup"}, false)
		require.NoError(t, err)
		assert.Equal(t, []string{"reindex", "backup"}, got)
	})

	t.Run("a repeated name is promoted once", func(t *testing.T) {
		got, err := Select(cfg, layout, []string{"backup", "backup"}, false)
		require.NoError(t, err)
		assert.Equal(t, []string{"backup"}, got)
	})

	t.Run("an unknown name is refused", func(t *testing.T) {
		_, err := Select(cfg, layout, []string{"nope"}, false)
		var unknown *UnknownEntryError
		require.ErrorAs(t, err, &unknown)
		assert.Equal(t, "nope", unknown.Name)
	})

	t.Run("an already-native name is refused and named its file", func(t *testing.T) {
		_, err := Select(cfg, layout, []string{"mine"}, false)
		var notStaged *NotStagedError
		require.ErrorAs(t, err, &notStaged)
		assert.Equal(t, "mine", notStaged.Name)
		assert.Equal(t, layout.RootPath, notStaged.File)
	})

	t.Run("one bad name refuses the whole request", func(t *testing.T) {
		_, err := Select(cfg, layout, []string{"backup", "nope"}, false)
		require.Error(t, err)
	})
}

// TestSelect_AllWithNothingStaged returns an empty selection rather than an
// error, so re-running `promote --all` on an already-converged config is a no-op
// a script can rely on.
func TestSelect_AllWithNothingStaged(t *testing.T) {
	layout := twoTierLayout(t, twoTierRoot, "")
	got, err := Select(loadLayout(t, layout), layout, nil, true)

	require.NoError(t, err)
	assert.Empty(t, got)
}

// TestSelect_ComposeGeneratedTaskIsNotStaged: a compose-backed task has no block
// of its own to move, so it is refused with no file to point at.
func TestSelect_ComposeGeneratedTaskIsNotStaged(t *testing.T) {
	dir := writeFileTree(t, map[string]string{
		"runwisp.toml": `[compose.stack]
file = "compose.yml"
`,
		"compose.yml": `services:
  web:
    image: nginx
`,
	})
	layout := NewLayout(filepath.Join(dir, "runwisp.toml"))
	cfg := loadLayout(t, layout)
	require.NotEmpty(t, cfg.Tasks, "the compose project must have produced a task")

	_, err := Select(cfg, layout, []string{cfg.Tasks[0].Name}, false)

	var notStaged *NotStagedError
	require.ErrorAs(t, err, &notStaged)
	assert.Empty(t, notStaged.File, "a compose-generated task has no defining block")
}
