// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: config.sql

package sqlcdb

import (
	"context"
)

const getConfigValue = `-- name: GetConfigValue :one

SELECT value FROM config_entries WHERE key = ?
`

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setConfigValue = `-- name: SetConfigValue :exec
INSERT INTO config_entries (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetConfigValue(ctx context.Context, arg SetConfigValueParams) error {
	_, err := q.db.ExecContext(ctx, setConfigValue, arg.Key, arg.Value)
	return err
}
