// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"time"

	"github.com/runwisp/runwisp/internal/model"
)

type ConfigEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Notification struct {
	ID              string     `json:"id"`
	Fingerprint     string     `json:"fingerprint"`
	Kind            string     `json:"kind"`
	Severity        string     `json:"severity"`
	TaskName        string     `json:"task_name"`
	RunID           string     `json:"run_id"`
	Title           string     `json:"title"`
	Body            string     `json:"body"`
	Count           int        `json:"count"`
	OccurrencesJson string     `json:"occurrences_json"`
	CreatedAt       time.Time  `json:"created_at"`
	LastOccurredAt  time.Time  `json:"last_occurred_at"`
	ReadAt          *time.Time `json:"read_at"`
}

type PendingLogUpload struct {
	ExecutionID    string `json:"execution_id"`
	UploadUrl      string `json:"upload_url"`
	LogPath        string `json:"log_path"`
	InsertedAtUnix int64  `json:"inserted_at_unix"`
}

type Run struct {
	ID            string            `json:"id"`
	ExecutionID   *string           `json:"execution_id"`
	TaskName      string            `json:"task_name"`
	Status        model.RunPhase    `json:"status"`
	EndReason     *model.EndReason  `json:"end_reason"`
	ExitCode      int               `json:"exit_code"`
	StartedAt     *time.Time        `json:"started_at"`
	EndedAt       *time.Time        `json:"ended_at"`
	TriggeredBy   model.TriggeredBy `json:"triggered_by"`
	CreatedAt     time.Time         `json:"created_at"`
	RetryAttempt  int               `json:"retry_attempt"`
	RetryOfRunID  *string           `json:"retry_of_run_id"`
	InstanceIndex int               `json:"instance_index"`
	ParamsJson    *string           `json:"params_json"`
	DeletedAt     *time.Time        `json:"deleted_at"`
}

type TaskRegistration struct {
	TaskName    string    `json:"task_name"`
	FirstSeenAt time.Time `json:"first_seen_at"`
}
