// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package sqlcdb

import (
	"context"
	"time"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT CAST(COUNT(*) AS INTEGER) FROM notifications WHERE read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, fingerprint, kind, severity, task_name, run_id, title, body, count, occurrences_json, created_at, last_occurred_at, read_at FROM notifications WHERE id = ?
`

func (q *Queries) GetNotificationByID(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Kind,
		&i.Severity,
		&i.TaskName,
		&i.RunID,
		&i.Title,
		&i.Body,
		&i.Count,
		&i.OccurrencesJson,
		&i.CreatedAt,
		&i.LastOccurredAt,
		&i.ReadAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (id, fingerprint, kind, severity, task_name, run_id,
  title, body, count, occurrences_json, created_at, last_occurred_at, read_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
`

type InsertNotificationParams struct {
	ID              string    `json:"id"`
	Fingerprint     string    `json:"fingerprint"`
	Kind            string    `json:"kind"`
	Severity        string    `json:"severity"`
	TaskName        string    `json:"task_name"`
	RunID           string    `json:"run_id"`
	Title           string    `json:"title"`
	Body            string    `json:"body"`
	Count           int       `json:"count"`
	OccurrencesJson string    `json:"occurrences_json"`
	CreatedAt       time.Time `json:"created_at"`
	LastOccurredAt  time.Time `json:"last_occurred_at"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, insertNotification,
		arg.ID,
		arg.Fingerprint,
		arg.Kind,
		arg.Severity,
		arg.TaskName,
		arg.RunID,
		arg.Title,
		arg.Body,
		arg.Count,
		arg.OccurrencesJson,
		arg.CreatedAt,
		arg.LastOccurredAt,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many

SELECT id, fingerprint, kind, severity, task_name, run_id, title, body, count, occurrences_json, created_at, last_occurred_at, read_at FROM notifications ORDER BY id DESC LIMIT ?
`

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: GPL-3.0-or-later
func (q *Queries) ListNotifications(ctx context.Context, limit int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Kind,
			&i.Severity,
			&i.TaskName,
			&i.RunID,
			&i.Title,
			&i.Body,
			&i.Count,
			&i.OccurrencesJson,
			&i.CreatedAt,
			&i.LastOccurredAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsBefore = `-- name: ListNotificationsBefore :many
SELECT id, fingerprint, kind, severity, task_name, run_id, title, body, count, occurrences_json, created_at, last_occurred_at, read_at FROM notifications WHERE id < ? ORDER BY id DESC LIMIT ?
`

type ListNotificationsBeforeParams struct {
	ID    string `json:"id"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListNotificationsBefore(ctx context.Context, arg ListNotificationsBeforeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsBefore, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Kind,
			&i.Severity,
			&i.TaskName,
			&i.RunID,
			&i.Title,
			&i.Body,
			&i.Count,
			&i.OccurrencesJson,
			&i.CreatedAt,
			&i.LastOccurredAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = ? WHERE read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, readAt *time.Time) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, readAt)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = ? WHERE id = ?
`

type MarkNotificationReadParams struct {
	ReadAt *time.Time `json:"read_at"`
	ID     string     `json:"id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ReadAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationUnread = `-- name: MarkNotificationUnread :execrows
UPDATE notifications SET read_at = NULL WHERE id = ?
`

func (q *Queries) MarkNotificationUnread(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationUnread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneNotificationsByAge = `-- name: PruneNotificationsByAge :execrows
DELETE FROM notifications WHERE last_occurred_at < ?
`

func (q *Queries) PruneNotificationsByAge(ctx context.Context, lastOccurredAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneNotificationsByAge, lastOccurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneNotificationsByCount = `-- name: PruneNotificationsByCount :execrows
DELETE FROM notifications WHERE id IN (
  SELECT id FROM notifications ORDER BY id DESC LIMIT -1 OFFSET ?
)
`

func (q *Queries) PruneNotificationsByCount(ctx context.Context, offset int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneNotificationsByCount, offset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectExistingForFingerprint = `-- name: SelectExistingForFingerprint :one
SELECT id, count, occurrences_json, created_at, run_id FROM notifications
WHERE fingerprint = ? AND last_occurred_at >= ?
ORDER BY last_occurred_at DESC LIMIT 1
`

type SelectExistingForFingerprintParams struct {
	Fingerprint    string    `json:"fingerprint"`
	LastOccurredAt time.Time `json:"last_occurred_at"`
}

type SelectExistingForFingerprintRow struct {
	ID              string    `json:"id"`
	Count           int       `json:"count"`
	OccurrencesJson string    `json:"occurrences_json"`
	CreatedAt       time.Time `json:"created_at"`
	RunID           string    `json:"run_id"`
}

func (q *Queries) SelectExistingForFingerprint(ctx context.Context, arg SelectExistingForFingerprintParams) (SelectExistingForFingerprintRow, error) {
	row := q.db.QueryRowContext(ctx, selectExistingForFingerprint, arg.Fingerprint, arg.LastOccurredAt)
	var i SelectExistingForFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Count,
		&i.OccurrencesJson,
		&i.CreatedAt,
		&i.RunID,
	)
	return i, err
}

const updateNotificationCoalesced = `-- name: UpdateNotificationCoalesced :exec
UPDATE notifications
SET count = ?, occurrences_json = ?, last_occurred_at = ?, title = ?, body = ?, read_at = NULL
WHERE id = ?
`

type UpdateNotificationCoalescedParams struct {
	Count           int       `json:"count"`
	OccurrencesJson string    `json:"occurrences_json"`
	LastOccurredAt  time.Time `json:"last_occurred_at"`
	Title           string    `json:"title"`
	Body            string    `json:"body"`
	ID              string    `json:"id"`
}

func (q *Queries) UpdateNotificationCoalesced(ctx context.Context, arg UpdateNotificationCoalescedParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationCoalesced,
		arg.Count,
		arg.OccurrencesJson,
		arg.LastOccurredAt,
		arg.Title,
		arg.Body,
		arg.ID,
	)
	return err
}
