// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_log_uploads.sql

package sqlcdb

import (
	"context"
)

const deletePendingLogUpload = `-- name: DeletePendingLogUpload :exec
DELETE FROM pending_log_uploads WHERE external_execution_id = ?
`

func (q *Queries) DeletePendingLogUpload(ctx context.Context, externalExecutionID string) error {
	_, err := q.db.ExecContext(ctx, deletePendingLogUpload, externalExecutionID)
	return err
}

const listPendingLogUploads = `-- name: ListPendingLogUploads :many
SELECT external_execution_id, upload_url, log_path, inserted_at FROM pending_log_uploads
`

func (q *Queries) ListPendingLogUploads(ctx context.Context) ([]PendingLogUpload, error) {
	rows, err := q.db.QueryContext(ctx, listPendingLogUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingLogUpload{}
	for rows.Next() {
		var i PendingLogUpload
		if err := rows.Scan(
			&i.ExternalExecutionID,
			&i.UploadUrl,
			&i.LogPath,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPendingLogUpload = `-- name: UpsertPendingLogUpload :exec
INSERT INTO pending_log_uploads (external_execution_id, upload_url, log_path, inserted_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(external_execution_id) DO UPDATE SET
  upload_url = excluded.upload_url,
  log_path = excluded.log_path,
  inserted_at = excluded.inserted_at
`

type UpsertPendingLogUploadParams struct {
	ExternalExecutionID string `json:"external_execution_id"`
	UploadUrl           string `json:"upload_url"`
	LogPath             string `json:"log_path"`
	InsertedAt          int64  `json:"inserted_at"`
}

func (q *Queries) UpsertPendingLogUpload(ctx context.Context, arg UpsertPendingLogUploadParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingLogUpload,
		arg.ExternalExecutionID,
		arg.UploadUrl,
		arg.LogPath,
		arg.InsertedAt,
	)
	return err
}
