// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pending_log_uploads.sql

package sqlcdb

import (
	"context"
)

const deletePendingLogUpload = `-- name: DeletePendingLogUpload :exec
DELETE FROM pending_log_uploads WHERE execution_id = ?
`

func (q *Queries) DeletePendingLogUpload(ctx context.Context, executionID string) error {
	_, err := q.db.ExecContext(ctx, deletePendingLogUpload, executionID)
	return err
}

const listPendingLogUploads = `-- name: ListPendingLogUploads :many
SELECT execution_id, upload_url, log_path, inserted_at_unix FROM pending_log_uploads
`

func (q *Queries) ListPendingLogUploads(ctx context.Context) ([]PendingLogUpload, error) {
	rows, err := q.db.QueryContext(ctx, listPendingLogUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingLogUpload{}
	for rows.Next() {
		var i PendingLogUpload
		if err := rows.Scan(
			&i.ExecutionID,
			&i.UploadUrl,
			&i.LogPath,
			&i.InsertedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPendingLogUpload = `-- name: UpsertPendingLogUpload :exec

INSERT INTO pending_log_uploads (execution_id, upload_url, log_path, inserted_at_unix)
VALUES (?, ?, ?, ?)
ON CONFLICT(execution_id) DO UPDATE SET
  upload_url = excluded.upload_url,
  log_path = excluded.log_path,
  inserted_at_unix = excluded.inserted_at_unix
`

type UpsertPendingLogUploadParams struct {
	ExecutionID    string `json:"execution_id"`
	UploadUrl      string `json:"upload_url"`
	LogPath        string `json:"log_path"`
	InsertedAtUnix int64  `json:"inserted_at_unix"`
}

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: GPL-3.0-or-later
func (q *Queries) UpsertPendingLogUpload(ctx context.Context, arg UpsertPendingLogUploadParams) error {
	_, err := q.db.ExecContext(ctx, upsertPendingLogUpload,
		arg.ExecutionID,
		arg.UploadUrl,
		arg.LogPath,
		arg.InsertedAtUnix,
	)
	return err
}
