// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"context"
	"time"
)

type Querier interface {
	CountRuns(ctx context.Context, taskName string) (int64, error)
	CountRunsFiltered(ctx context.Context, arg CountRunsFilteredParams) (int64, error)
	CountUnreadNotifications(ctx context.Context) (int64, error)
	CreateRun(ctx context.Context, arg CreateRunParams) error
	DeletePendingLogUpload(ctx context.Context, externalExecutionID string) error
	DeleteRun(ctx context.Context, id string) error
	EnsureTaskRegistered(ctx context.Context, arg EnsureTaskRegisteredParams) error
	GetConfigValue(ctx context.Context, key string) (string, error)
	GetLastRunByTask(ctx context.Context, taskName string) (Run, error)
	GetNotificationByID(ctx context.Context, id string) (Notification, error)
	GetPendingRuns(ctx context.Context) ([]Run, error)
	GetRun(ctx context.Context, id string) (Run, error)
	GetRunByExternalExecutionID(ctx context.Context, externalExecutionID *string) (Run, error)
	GetRunSummary(ctx context.Context) (GetRunSummaryRow, error)
	GetTaskRegistration(ctx context.Context, taskName string) (TaskRegistration, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	ListNotifications(ctx context.Context, limit int64) ([]Notification, error)
	ListNotificationsBefore(ctx context.Context, arg ListNotificationsBeforeParams) ([]Notification, error)
	ListPendingLogUploads(ctx context.Context) ([]PendingLogUpload, error)
	MarkAllNotificationsRead(ctx context.Context, readAt *time.Time) error
	MarkCrashedRuns(ctx context.Context, endAt *time.Time) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	MarkNotificationUnread(ctx context.Context, id string) (int64, error)
	PruneNotificationsByAge(ctx context.Context, lastOccurredAt time.Time) (int64, error)
	PruneNotificationsByCount(ctx context.Context, offset int64) (int64, error)
	PurgeExpiredSoftDeletes(ctx context.Context, deletedAt *time.Time) ([]PurgeExpiredSoftDeletesRow, error)
	SelectExistingForFingerprint(ctx context.Context, arg SelectExistingForFingerprintParams) (SelectExistingForFingerprintRow, error)
	SelectOldRunsByAge(ctx context.Context, arg SelectOldRunsByAgeParams) ([]Run, error)
	SelectOldRunsByCount(ctx context.Context, arg SelectOldRunsByCountParams) ([]Run, error)
	SetConfigValue(ctx context.Context, arg SetConfigValueParams) error
	UpdateNotificationCoalesced(ctx context.Context, arg UpdateNotificationCoalescedParams) error
	UpdateRun(ctx context.Context, arg UpdateRunParams) error
	UpsertPendingLogUpload(ctx context.Context, arg UpsertPendingLogUploadParams) error
}

var _ Querier = (*Queries)(nil)
