// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs_soft_delete.sql

package sqlcdb

import (
	"context"
	"time"
)

const purgeExpiredSoftDeletes = `-- name: PurgeExpiredSoftDeletes :many
DELETE FROM runs WHERE deleted_at IS NOT NULL AND deleted_at <= ?
RETURNING id, task_name, created_at
`

type PurgeExpiredSoftDeletesRow struct {
	ID        string    `json:"id"`
	TaskName  string    `json:"task_name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) PurgeExpiredSoftDeletes(ctx context.Context, deletedAt *time.Time) ([]PurgeExpiredSoftDeletesRow, error) {
	rows, err := q.db.QueryContext(ctx, purgeExpiredSoftDeletes, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurgeExpiredSoftDeletesRow{}
	for rows.Next() {
		var i PurgeExpiredSoftDeletesRow
		if err := rows.Scan(&i.ID, &i.TaskName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
