// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/runwisp/runwisp/internal/model"
)

const countRuns = `-- name: CountRuns :one
SELECT COUNT(*) FROM runs WHERE task_name = ? AND deleted_at IS NULL
`

func (q *Queries) CountRuns(ctx context.Context, taskName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRuns, taskName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :exec

INSERT INTO runs (id, external_execution_id, task_name, status, end_reason,
  exit_code, start_at, end_at, triggered_by, created_at, retry_attempt,
  retry_of_run_id, instance_index)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRunParams struct {
	ID                  string            `json:"id"`
	ExternalExecutionID *string           `json:"external_execution_id"`
	TaskName            string            `json:"task_name"`
	Status              model.RunPhase    `json:"status"`
	EndReason           *model.EndReason  `json:"end_reason"`
	ExitCode            int               `json:"exit_code"`
	StartAt             *time.Time        `json:"start_at"`
	EndAt               *time.Time        `json:"end_at"`
	TriggeredBy         model.TriggeredBy `json:"triggered_by"`
	CreatedAt           time.Time         `json:"created_at"`
	RetryAttempt        int               `json:"retry_attempt"`
	RetryOfRunID        *string           `json:"retry_of_run_id"`
	InstanceIndex       int               `json:"instance_index"`
}

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.ExternalExecutionID,
		arg.TaskName,
		arg.Status,
		arg.EndReason,
		arg.ExitCode,
		arg.StartAt,
		arg.EndAt,
		arg.TriggeredBy,
		arg.CreatedAt,
		arg.RetryAttempt,
		arg.RetryOfRunID,
		arg.InstanceIndex,
	)
	return err
}

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM runs WHERE id = ?
`

func (q *Queries) DeleteRun(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRun, id)
	return err
}

const getLastRunByTask = `-- name: GetLastRunByTask :one
SELECT id, external_execution_id, task_name, status, end_reason, exit_code, start_at, end_at, triggered_by, created_at, retry_attempt, retry_of_run_id, instance_index, deleted_at FROM runs WHERE task_name = ? AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastRunByTask(ctx context.Context, taskName string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLastRunByTask, taskName)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ExternalExecutionID,
		&i.TaskName,
		&i.Status,
		&i.EndReason,
		&i.ExitCode,
		&i.StartAt,
		&i.EndAt,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.RetryAttempt,
		&i.RetryOfRunID,
		&i.InstanceIndex,
		&i.DeletedAt,
	)
	return i, err
}

const getPendingRuns = `-- name: GetPendingRuns :many
SELECT id, external_execution_id, task_name, status, end_reason, exit_code, start_at, end_at, triggered_by, created_at, retry_attempt, retry_of_run_id, instance_index, deleted_at FROM runs WHERE status = 'pending' AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetPendingRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ExternalExecutionID,
			&i.TaskName,
			&i.Status,
			&i.EndReason,
			&i.ExitCode,
			&i.StartAt,
			&i.EndAt,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.RetryAttempt,
			&i.RetryOfRunID,
			&i.InstanceIndex,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, external_execution_id, task_name, status, end_reason, exit_code, start_at, end_at, triggered_by, created_at, retry_attempt, retry_of_run_id, instance_index, deleted_at FROM runs WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ExternalExecutionID,
		&i.TaskName,
		&i.Status,
		&i.EndReason,
		&i.ExitCode,
		&i.StartAt,
		&i.EndAt,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.RetryAttempt,
		&i.RetryOfRunID,
		&i.InstanceIndex,
		&i.DeletedAt,
	)
	return i, err
}

const getRunByExternalExecutionID = `-- name: GetRunByExternalExecutionID :one
SELECT id, external_execution_id, task_name, status, end_reason, exit_code, start_at, end_at, triggered_by, created_at, retry_attempt, retry_of_run_id, instance_index, deleted_at FROM runs WHERE external_execution_id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetRunByExternalExecutionID(ctx context.Context, externalExecutionID *string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByExternalExecutionID, externalExecutionID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ExternalExecutionID,
		&i.TaskName,
		&i.Status,
		&i.EndReason,
		&i.ExitCode,
		&i.StartAt,
		&i.EndAt,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.RetryAttempt,
		&i.RetryOfRunID,
		&i.InstanceIndex,
		&i.DeletedAt,
	)
	return i, err
}

const getRunSummary = `-- name: GetRunSummary :one
SELECT
  CAST(COUNT(*) AS INTEGER) AS total,
  CAST(COALESCE(SUM(CASE WHEN end_reason = 'success' THEN 1 ELSE 0 END), 0) AS INTEGER) AS success,
  CAST(COALESCE(SUM(CASE WHEN end_reason IN ('failed','crashed','timeout','log_overflow')
                         THEN 1 ELSE 0 END), 0) AS INTEGER) AS failed,
  MAX(CASE WHEN end_reason IN ('failed','crashed','timeout','log_overflow')
           THEN end_at END) AS last_failure
FROM runs WHERE deleted_at IS NULL
`

type GetRunSummaryRow struct {
	Total       int64       `json:"total"`
	Success     int64       `json:"success"`
	Failed      int64       `json:"failed"`
	LastFailure interface{} `json:"last_failure"`
}

func (q *Queries) GetRunSummary(ctx context.Context) (GetRunSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getRunSummary)
	var i GetRunSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Success,
		&i.Failed,
		&i.LastFailure,
	)
	return i, err
}

const markCrashedRuns = `-- name: MarkCrashedRuns :execrows
UPDATE runs SET status = 'ended', end_reason = 'crashed', end_at = ?, exit_code = -2
WHERE status = 'running' AND end_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) MarkCrashedRuns(ctx context.Context, endAt *time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCrashedRuns, endAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRun = `-- name: UpdateRun :exec
UPDATE runs SET external_execution_id = ?, task_name = ?, status = ?,
  end_reason = ?, exit_code = ?, start_at = ?, end_at = ?, triggered_by = ?,
  created_at = ?, retry_attempt = ?, retry_of_run_id = ?, instance_index = ?
WHERE id = ?
`

type UpdateRunParams struct {
	ExternalExecutionID *string           `json:"external_execution_id"`
	TaskName            string            `json:"task_name"`
	Status              model.RunPhase    `json:"status"`
	EndReason           *model.EndReason  `json:"end_reason"`
	ExitCode            int               `json:"exit_code"`
	StartAt             *time.Time        `json:"start_at"`
	EndAt               *time.Time        `json:"end_at"`
	TriggeredBy         model.TriggeredBy `json:"triggered_by"`
	CreatedAt           time.Time         `json:"created_at"`
	RetryAttempt        int               `json:"retry_attempt"`
	RetryOfRunID        *string           `json:"retry_of_run_id"`
	InstanceIndex       int               `json:"instance_index"`
	ID                  string            `json:"id"`
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRun,
		arg.ExternalExecutionID,
		arg.TaskName,
		arg.Status,
		arg.EndReason,
		arg.ExitCode,
		arg.StartAt,
		arg.EndAt,
		arg.TriggeredBy,
		arg.CreatedAt,
		arg.RetryAttempt,
		arg.RetryOfRunID,
		arg.InstanceIndex,
		arg.ID,
	)
	return err
}
