// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs_retention.sql

package sqlcdb

import (
	"context"
	"time"
)

const selectOldRunsByAge = `-- name: SelectOldRunsByAge :many

SELECT id, external_execution_id, task_name, status, end_reason, exit_code, start_at, end_at, triggered_by, created_at, retry_attempt, retry_of_run_id, instance_index, params_json, deleted_at FROM runs
WHERE task_name = ? AND created_at < ? AND status = 'ended' AND deleted_at IS NULL
LIMIT ?
`

type SelectOldRunsByAgeParams struct {
	TaskName  string    `json:"task_name"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int64     `json:"limit"`
}

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: GPL-3.0-or-later
// Only terminal (ended) runs are eligible for retention: a run that is still
// pending or running must never have its row or live log files removed.
func (q *Queries) SelectOldRunsByAge(ctx context.Context, arg SelectOldRunsByAgeParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, selectOldRunsByAge, arg.TaskName, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ExternalExecutionID,
			&i.TaskName,
			&i.Status,
			&i.EndReason,
			&i.ExitCode,
			&i.StartAt,
			&i.EndAt,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.RetryAttempt,
			&i.RetryOfRunID,
			&i.InstanceIndex,
			&i.ParamsJson,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectOldRunsByCount = `-- name: SelectOldRunsByCount :many
SELECT id, external_execution_id, task_name, status, end_reason, exit_code, start_at, end_at, triggered_by, created_at, retry_attempt, retry_of_run_id, instance_index, params_json, deleted_at FROM runs
WHERE task_name = ? AND status = 'ended' AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SelectOldRunsByCountParams struct {
	TaskName string `json:"task_name"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

// Count-based retention likewise ranges over ended runs only, so in-flight
// runs neither count against the cap nor get purged.
func (q *Queries) SelectOldRunsByCount(ctx context.Context, arg SelectOldRunsByCountParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, selectOldRunsByCount, arg.TaskName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ExternalExecutionID,
			&i.TaskName,
			&i.Status,
			&i.EndReason,
			&i.ExitCode,
			&i.StartAt,
			&i.EndAt,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.RetryAttempt,
			&i.RetryOfRunID,
			&i.InstanceIndex,
			&i.ParamsJson,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
