// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_registrations.sql

package sqlcdb

import (
	"context"
	"time"
)

const ensureTaskRegistered = `-- name: EnsureTaskRegistered :exec

INSERT OR IGNORE INTO task_registrations (task_name, first_seen_at)
VALUES (?, ?)
`

type EnsureTaskRegisteredParams struct {
	TaskName    string    `json:"task_name"`
	FirstSeenAt time.Time `json:"first_seen_at"`
}

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: Apache-2.0
func (q *Queries) EnsureTaskRegistered(ctx context.Context, arg EnsureTaskRegisteredParams) error {
	_, err := q.db.ExecContext(ctx, ensureTaskRegistered, arg.TaskName, arg.FirstSeenAt)
	return err
}

const getTaskRegistration = `-- name: GetTaskRegistration :one
SELECT task_name, first_seen_at FROM task_registrations WHERE task_name = ?
`

func (q *Queries) GetTaskRegistration(ctx context.Context, taskName string) (TaskRegistration, error) {
	row := q.db.QueryRowContext(ctx, getTaskRegistration, taskName)
	var i TaskRegistration
	err := row.Scan(&i.TaskName, &i.FirstSeenAt)
	return i, err
}
