// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_boot_ids.sql

package sqlcdb

import (
	"context"
)

const getTaskBootID = `-- name: GetTaskBootID :one

SELECT boot_id FROM task_boot_ids WHERE task_name = ?
`

// SPDX-FileCopyrightText: PoppyCake, s.r.o.
// SPDX-License-Identifier: GPL-3.0-or-later
func (q *Queries) GetTaskBootID(ctx context.Context, taskName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskBootID, taskName)
	var boot_id string
	err := row.Scan(&boot_id)
	return boot_id, err
}

const setTaskBootID = `-- name: SetTaskBootID :exec
INSERT INTO task_boot_ids (task_name, boot_id) VALUES (?, ?)
ON CONFLICT(task_name) DO UPDATE SET boot_id = excluded.boot_id
`

type SetTaskBootIDParams struct {
	TaskName string `json:"task_name"`
	BootID   string `json:"boot_id"`
}

func (q *Queries) SetTaskBootID(ctx context.Context, arg SetTaskBootIDParams) error {
	_, err := q.db.ExecContext(ctx, setTaskBootID, arg.TaskName, arg.BootID)
	return err
}
